#!/usr/bin/env bash
# Rebuild index.md from prefer/*.md frontmatter. Atomic.
#
# With a state dir, the index is activation-tiered: an entry earns always-on
# ("habitual") status through use, scored ACT-R-style — each event contributes
# weight/age^0.5 (power-law decay), so recency and frequency raise an entry and
# disuse sinks it back. Events and weights: user-confirmed Evidence 2.0,
# usage.log applied 1.0, excepted 0.5, created 0.3. Habitual needs a score >= 1
# and a seat within RATHER_THAN_HABIT_MAX (default 15); 2+ overridden events
# making up half or more of the outcomes force an entry cold regardless.
# Everything else lists cold — category, count, slugs — to be consulted via
# query.sh when the work touches it. Without a state dir: the flat list.
set -euo pipefail
export LC_NUMERIC=C  # decimal points, not commas — the scores are sorted with -g

root="${1:?usage: rebuild-index.sh <root> [<state-dir>]}"
state="${2:-}"
prefer="$root/prefer"
index="$root/index.md"
tmp="$index.tmp.$$"
habit_max="${RATHER_THAN_HABIT_MAX:-15}"
today="$(date +%Y-%m-%d)"

activation() { # <file> <slug> → "score applied overridden"
  local f="$1" slug="$2"
  {
    awk '/^created:[[:space:]]*/{sub(/^created:[[:space:]]*/,""); print $0, 0.3; exit}' "$f"
    awk '/^## Evidence/{fl=1; next} /^## /{fl=0} fl && $1=="-"{print $2, 2.0}' "$f"
    if [ -f "$state/usage.log" ]; then
      awk -v s="$slug" '
        $2==s && $3=="applied"{print $1, 1.0}
        $2==s && $3=="excepted"{print $1, 0.5}
        $2==s && $3=="overridden"{print $1, "O"}' "$state/usage.log"
    fi
  } | awk -v today="$today" '
    function jdn(y, m, d,  a, yy, mm) {
      a = int((14 - m) / 12); yy = y + 4800 - a; mm = m + 12 * a - 3
      return d + int((153 * mm + 2) / 5) + 365 * yy + int(yy / 4) - int(yy / 100) + int(yy / 400) - 32045
    }
    function datejdn(s,  p) { split(s, p, "-"); return jdn(p[1] + 0, p[2] + 0, p[3] + 0) }
    BEGIN { tj = datejdn(today) }
    $1 !~ /^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]$/ { next }
    $2 == "O" { o++; next }
    { age = tj - datejdn($1); if (age < 1) age = 1; S += $2 * age ^ -0.5; if ($2 == 1.0) a++ }
    END { printf "%.4f %d %d\n", S + 0, a + 0, o + 0 }'
}

records="$(mktemp)"
trap 'rm -f "$records" "$tmp"' EXIT

if [ -d "$prefer" ]; then
  for f in "$prefer"/*.md; do
    [ -e "$f" ] || continue
    slug="$(basename "$f" .md)"
    topic="$(awk '/^topic:[[:space:]]*/{sub(/^topic:[[:space:]]*/,""); print; exit}' "$f")"
    scope="$(awk '/^scope:[[:space:]]*/{sub(/^scope:[[:space:]]*/,""); print; exit}' "$f")"
    conf="$(awk '/^confidence:[[:space:]]*/{sub(/^confidence:[[:space:]]*/,""); print; exit}' "$f")"
    cat_="$(awk '/^category:[[:space:]]*/{sub(/^category:[[:space:]]*/,""); print; exit}' "$f")"
    excepts="$(awk '/^## Except/{flag=1; next} /^## /{flag=0} flag && /^- /{n++} END{print n+0}' "$f")"
    # The Except situations ride in the index line (truncated). The index is
    # the cheap path every turn — it must carry the misfire guard itself, not
    # just count it; the Except reasons stay in the file.
    excsum="$(awk '/^## Except/{flag=1; next} /^## /{flag=0} flag && /^- /{sub(/^- /,""); s = s (s ? "; " : "") $0} END{print s}' "$f")"
    [ "${#excsum}" -gt 120 ] && excsum="${excsum:0:119}…"

    line="- ${slug}: ${topic:-"(no topic)"} [${scope:-"?"}]"
    [ "${excepts}" -gt 0 ] && line="$line [${excepts} except: ${excsum}]"
    [ "${conf:-}" = "inferred" ] && line="$line [inferred]"

    contested=0
    if [ -n "$state" ]; then
      read -r S applied overridden <<EOF
$(activation "$f" "$slug")
EOF
      [ "$overridden" -ge 2 ] && [ $((overridden * 2)) -ge $((applied + overridden)) ] && contested=1
    else
      S=1
    fi
    printf '%s\t%s\t%s\t%s\t%s\n' "$S" "$contested" "${cat_:-uncategorized}" "$slug" "$line" >> "$records"
  done
fi

emit_grouped() { # stdin: "category<TAB>line" — category-grouped bullet list
  sort -s -t"$(printf '\t')" -k1,1 | awk -F'\t' '
    $1 != prev { print "#### " $1; prev = $1 }
    { print $2 }'
}

{
  echo "<!-- generated by rather-than — do not edit -->"
  if [ -z "$state" ]; then
    cut -f3,5 "$records" | emit_grouped
  elif [ -s "$records" ]; then
    hot="$(mktemp)"; cold="$(mktemp)"
    sort -t"$(printf '\t')" -k1,1gr "$records" | awk -F'\t' \
      -v max="$habit_max" -v hot="$hot" -v cold="$cold" '
      $1 + 0 >= 1 && $2 == 0 && n < max { n++; print $3 "\t" $5 > hot; next }
      { print $3 "\t" $4 > cold }'
    if [ -s "$hot" ]; then
      echo "## habitual — earned by use; active every turn, within observed-in"
      emit_grouped < "$hot"
    fi
    if [ -s "$cold" ]; then
      echo "## cold — not active; query the category before use when the work touches it"
      sort "$cold" | awk -F'\t' '
        function emit() { print "- " prev ": " n " (" s ")" }
        $1 != prev { if (prev != "") emit(); prev = $1; n = 0; s = "" }
        { n++; s = s (s ? ", " : "") $2 }
        END { if (prev != "") emit() }'
    fi
    rm -f "$hot" "$cold"
  fi
} > "$tmp"

mv "$tmp" "$index"
